### PR TITLE
Added a travis.yml configuration.

### PR DESCRIPTION
**Pull request by squidarth**
Added a travis.yml configuration.

### CODE REVIEW

**Comment by minrk** [comment]
You will need a requirements.txt to get the ipython/jupyter dependencies. See the one in jupyter_nbconvert for an example.

I'm not sure if this is going to work because apt-get install pyqt doesn't make pyqt available to the virtualenv where I think the tests are run.

**Comment by takluyver** [comment]
One way we could do this is to install Miniconda and use that to install pyqt. It's kind of a hack, but it works. Here's an example that does it: https://github.com/jhamrick/dbtools/blob/master/.travis.yml

**Comment by squidarth** [comment]
What did you do to install pyqt before this repo was split out?  Still a little stuck on the best approach and was digging through old versions of github.com/ipython/ipython

**Comment by takluyver** [comment]
We didn't ;-) - the Qt console wasn't tested on Travis. We also run tests on our [Jenkins server](https://jenkins.jupyter.org/), where we can install Qt. But now that the Qt console is a separate repo, doing this doesn't hold up tests for the rest of IPython, so it makes sense.

**Comment by squidarth** [comment]
@takluyver Finally got the tests to pass! Lmk what you think

**Comment by Carreau** [comment]
Does it uses docker on travis ? Or should we set `sudo: false` ?

Also sidenote, I guess on docker build we could use cached dirs to speed-up rebuild.

**Comment by squidarth** [comment]
Ah good catch--I was previously installing pyqt via `apt-get`. `sudo` can be set to `false`.  It's not using docker, although that would be a good thing to do as a follow-up

**Comment by Carreau** [comment]
depends also on when the repo was created, I think they might default to sudo:false now.

**Comment by Carreau** [comment]
decreased the time by ~30 sec /run roughly 1min15 total.

**Comment by minrk** [comment]
Great, thanks for getting this started. Since it's using conda, you can probably remove the use of travis-wheels, and install a few dependencies with `conda install pyzmq sphinx pygments`.

**Comment by squidarth** [comment]
Cool--went ahead and made that change

**Comment by takluyver** [comment]
:+1:

**Comment by minrk** [comment]
Great!

**Pull request merged**
